name: Smarts Downloader

on:
  workflow_dispatch:
    inputs:
      url:
        description: "URL to download"
        required: true
        default: "https://google.com"
      filename:
        description: "Output file name"
        required: true
        default: "index.html"

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download File using Curl
        run: |
          curl -L "${{ github.event.inputs.url }}" -o "${{ github.event.inputs.filename }}"

      - name: Upload result as artifact
        uses: actions/upload-artifact@v4
        with:
          name: downloaded-file
          path: ${{ github.event.inputs.filename }}
